<?php
$keywords=array("Banks","Broke","Unemployment","Property Crash","Negative Equity",
"redundancy","pay cuts","debt","negative equity","jobless",
"Banking","pay","tax USC","euro","rates",
"Mortgages","Pay-cuts","Job losses","Increased taxes","Banks",
"struggle","simpler","isolation","strength","stress",
"Unemployment","Instability","Insecurity","Banking","Disillusionment",
"Unemployment","Redundancies","Depression","Emigration","Bank Guarantee",
"Fuck","Banks","Fat cats","Anglo","Property",
"financial","crisis","poverty","unfair","burden",
"Reality","loss","failure","neglect","inevitable",
"Money","Bankers","Bonuses","House prices","unemployment",
"Opportunity","Job Losses","Less Money","Emigration","Dole",
"Extravagance","Bankers","Bailout","Accountability","Cost of Living",
"Depression","property","economy","unemployment","Anglo",
"Myopia","Greed","Incompetence","Laziness","Negligence",
"Society","Anger","Resigned","Hope","Pain",
"Banks","unemployment","austerity","property","Anglo",
"government","spending","improves","recovery","prospects",
"Unemployment","Emigration","Increased taxes","Business closures","banks",
"Capitalist","exploitation","crisis","crooked","gougers",
"Pension","Anger","Greed","Arrogance","Incompetence",
"Banks","Mortgages","Troika","NAMA","Closures",
"crime and drug rate up","high prices","low income","lack of motivation","stress",
"Depressing","Endless","Broke","Banks","Unemployment",
"Banking","property collapse","job loss",
"Stress","Loss/unemployment","Banks","Mortgages","Government",
"Money","Banks","Tax","Government","Emigration",
"Negative equity","Bondholders","Bailout","Unemployment","Gloom",
"Money","Jobless","Redundancies","Welfare","Leprechauns",
"Bubble","soft-landing","AngloIrishBank","emigration","unemployment",
"Imagination is greater than detail",
"poverty","fat cats","shops closure","struggle","Lidl",
"immigration","big debt","back to basics","higher petty crime","no jobs",
"What","Recession","Scam","Pensions","Fraud",
"Bleak","Saddening","Unnecessary","Greed","No Accountability",
"immigration","Demoralised","Trapped","Unhappy","Bored",
"Debt","Unempoyment","Emmigration","Bankers","Skint",
"Hopeless","Suicidal","Homeless","Barbarian","Empty",
"Hunger","Homelessness","Robbery","Unemployment","High cost of living",
"Homeless","Money","Government","Help","Banks",
"Dole","No job","No money","Credit card debt","Government are useless",
"Tough","Poor","Spiteful","Pessimistic","Begrudgingly",
"Country Ran By Many Fools",
"Fianna Fail","Fine Gael","No money","No order","No plan",
"Poverty","Government distrust","Depression","Rise in crime rate","Starting fresh",
"depressing","depressing","depressing","depressing","depressing",
"Is a Barrell of Laughs",
"Broke","Bankers","Unemployment","Worry","Emigration",
"jobs","study","skills","new job","money",
"Greece","Great Depression","EU","Money","Poor",
"high unemployment","less money in pockets thus less spending","cut backs","increase level of corruption","depression",
"cold","confusion","despair","stress","worry",
"prices","unemployment","great depression","emigration","macroeconomics",
"Broke","Politicians","Banks","Unemployment","Emmigration",
"hardships","no joy","find somewhere else to live","no food","no love",
"unemployment","poverty","depression","stress","crime",
"Burst","Free fall","Celtic tiger","Nama","Troika",
"people appreciate one another more and stick together/help one another out  encourages social groups","People feel trapped in jobs afraid to leave","More people going back to college to reeducate themselves in a new career field","Less needless spending happening","no 'keeping up with,the Jones'","Start to value what you have and not take it for granted",
"Hopeless","Misery","Terrible","fragile","mess",
"Poverty","Hunger","Hope","Greed","Time",
"Money","Costs","Poor","Rich","Government",
"unemployment","cuts","savings","welfare","education",
"hardship","employment","emmigration","financial","crisis",
"Jobs","Household charge","Water rates","Charity Shops","Government",
"Job loss","Poverty","homeless","reduction of income","unemployement",
"surprising","disappointing","jobless","career-less","prospect-less",
"bad government","high tax","no jobs","new taxes, water charge, property tax","no good politicians",
"no jobs","no money","government​",
"Banks","America","Employment","Government","Households",
"Dole","Poor","Cutbacks","Debt","Merkel",
"Tax","Jobs","Government","Increase","Depression",
"Capitalism","Market","Welfare","Finance","Austerity",
"True","Money","Government","Management","Time",
"Intolerant","Uncaring","Hypocritical","Selfish","Greedy",
"TOUGH","MONEY","TROIKA","EMIGRATION","POLITICIANS");
$targets=array('eleven','six','two');
foreach ( $targets as $string ) 
{
  foreach ( $keywords as $keyword ) 
  {
    if ( strpos( $string, $keyword ) !== FALSE )
     { echo "The word appeared !!" }
  }
}
?>
